### ISSUE TITLE
Steam Deck input doesn't work at all after installing 

### ISSUE THREAD

**Issue by Mothamoz** [scawp/Steam-Deck.Auto-Disable-Steam-Controller#11]
Previous version of the script worked fine, the new one however disables my steam decks input completely without any external devices being connected.

I'm using a steam deck oled.

If any info is needed let me know and I'll be happy to assist.

**Comment by MisterFloppy** [comment]
I can confirm that the new script does not work on non-oled Steam Deck, too.

**Comment by MisterFloppy** [comment]
I did some searches in Google for "28de/1205 AND steam deck", all results obviously follow the same pattern:
vendor 0x28de product 0x1205 version 0x110
Sources:
https://wiki.archlinux.org/title/Steam_Deck
https://gitlab.com/postmarketOS/pmaports/-/issues/2657

Maybe instead of hardcoding the known full Product IDs into disable_steam_input.sh you could use "28de/1205" with a wildcard?

**Comment by scawp** [comment]
That is a very good point, for some reason I had it in my head that the Steam Controller has the same Product ID, so was trying to avoid the script not working with it, but appears not to be the case. Cheers, I'll do that!

**Comment by scawp** [comment]
Done!

**Comment by Mothamoz** [comment]
Amazing! Going to try it out later today and report back if @MisterFloppy doesn't beat me to it 😄

**Comment by MisterFloppy** [comment]
@scawp: Well done, your newest script is still working correctly!

@Mothamoz: First :-)
